### ISSUE TITLE
Register: unable to resolve relative import with oxc-resolver

### ISSUE THREAD

**Issue by fargito** [swc-project/swc-node#804]
## Context

When updating `@swc-node/register` from version `1.10.0` to `1.10.2`, relative typescript imports are no longer resolved.

When using a relative import, I get:
```bash
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
Error: Cannot find module './shared': ./shared cannot be resolved in file:///home/runner/work/rust-cdk-serverless/rust-cdk-serverless/iac/index.ts
    at resolve (file:///home/runner/work/rust-cdk-serverless/rust-cdk-serverless/node_modules/.pnpm/@swc-node+register@1.10.2_@swc+core@1.5.0_@swc+types@0.1.6_typescript@5.5.3/node_modules/@swc-node/register/esm/esm.mjs:208:15)
    at async nextResolve (node:internal/modules/esm/hooks:866:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:304:24)
    at async handleMessage (node:internal/modules/esm/worker:196:18)
```

- errored PR: https://github.com/fargito/rust-cdk-serverless/pull/287 
- CI job: https://github.com/fargito/rust-cdk-serverless/actions/runs/9821902780/job/27118080233?pr=287

## Investigation

The issue has probably been introduced by #798, more precisely [here](https://github.com/swc-project/swc-node/pull/798/files#diff-39fad42aba9db636f50b7209d5b35a6d43d4ba60823a0ab3e9d840ef4c09ee6dL171-L179).

I'm a bit puzzled, because the call to `resolver.async` is done with the correct arguments according to [the oxc-resolver docs](https://docs.rs/oxc_resolver/latest/oxc_resolver/struct.ResolverGeneric.html#tymethod.resolve):
- `directory` must be an absolute path to a directory where the specifier is resolved against. For CommonJS modules, it is the __dirname variable that contains the absolute path to the folder containing current module. For ECMAScript modules, it is the value of import.meta.url. In my case, it gives the expected value, i.e. `/home/runner/work/rust-cdk-serverless/rust-cdk-serverless/iac`
- `identifier`: in my case it is `./shared`

This looks correct according to the oxc-resolver docs, but oxc-resolver cannot find it. Maybe the ts config is incorrectly passed to the resolver?

I will try and set up a minimal reproduction in the coming days.

**Comment by psychobolt** [comment]
Unfortunately, I can't use the latest version of register because `oxc-resolver` doesn't support Yarn PnP: https://github.com/oxc-project/oxc-resolver/issues/53 . Even a simple import in my setup e.g. `import { $} from 'execa'` will fail:

```sh
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
Error: Cannot find module 'execa': execa cannot be resolved in file:///Users/mitran/Projects/vite-storybook-boilerplate/bin/bootstrap.ts
    at resolve (file:///Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-node-register-virtual-f17b414b8d/node_modules/@swc-node/register/esm/esm.mjs:208:15)
    at async nextResolve (node:internal/modules/esm/hooks:866:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:304:24)
    at async handleMessage (node:internal/modules/esm/worker:196:18)

Node.js v20.15.0
```

**Comment by fargito** [comment]
@psychobolt I'm using pnpm, so maybe it is a separate issue

**Comment by fargito** [comment]
I have set up a minimal reproduction: https://github.com/fargito/swc-node-relative-import-issue-repro

**Comment by fargito** [comment]
Thanks @Brooooooklyn! This fixed it for me.
