### ISSUE TITLE
`@swc-node/register@1.8.0` `/esm-register` does not recognise `tsconfig.json` paths

### ISSUE THREAD

**Issue by mylesj** [swc-project/swc-node#753]
I was playing with the latest and greatest and notice that when running via: 

```none
node --import @swc-node/register/esm-register src/index.ts
```

… `tsconfig.json` path aliases are not recognised, _e.g._

```json
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"]
    }
  },
}
```

[minimal reproducible example](https://github.com/mylesj/issue-swc-node-1)

<details>
  <summary>Stack trace</summary>

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/src/common' imported from /Users/myles/dev/issue-swc-node-1/src/index.ts
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at resolve (file:///Users/myles/dev/issue-swc-node-1/node_modules/.pnpm/@swc-node+register@1.8.0_@swc+core@1.3.107_@swc+types@0.1.5_typescript@5.3.3/node_modules/@swc-node/register/esm/esm.mjs:44:12)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///src/common'
}
```

</details>

> _Also of note: I am aware that native ESM would typically expect file-extensions to be specified in the import, but including them doesn't help in this case - though I think the expectation of `swc` would be not to care either way?_

**Comment by yeliex** [comment]
i would create a pr to solve this today

**Comment by yeliex** [comment]
besides, it is not recommended to use path alias in node, because nodejs runtime not support it actually

**Comment by yeliex** [comment]
it is a bug caused by #722

@Brooooooklyn maybe we should consider revert it, and add more test cases. it causes many unexpected results about resolve and compile. relate: #752 #734 #727

**Comment by galaxy-s10** [comment]
same problem

**Comment by alfaproject** [comment]
I've just stumbled upon this )':

**Comment by cghiurea** [comment]
> I've just stumbled upon this )':

You could use this `node --watch --no-warnings=ExperimentalWarning --loader ts-node/esm src/server.ts` as it will work depending on your project.

**Comment by alfaproject** [comment]
Well, TS paths resolution doesn't work and that's why I was trying `swc-node` to begin with:
```
❯ node --no-warnings=ExperimentalWarning --loader ts-node/esm ./apps/lambda-api/src/extract-schema.ts

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: Cannot find module '/Users/joaodias/the-mill/lambda-gaming.nosync/apps/lambda-api/src/schemas/schema' imported from /Users/joaodias/the-mill/lambda-gaming.nosync/apps/lambda-api/src/extract-schema.ts
```

**Comment by yeliex** [comment]
https://github.com/swc-project/swc-node/pull/754 should fix this, i would test later. feedback please.
